title: Abhishesh's Homepage
description: Bookmark this to keep watch on new updates

theme: minima

minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: abhishesh
    github: abhishesh
    linkedin: abhishesh
    keybase: abhishesh

plugins:
 - jekyll-feed
 - jekyll-seo-tag
