title: Abhishesh's Homepage
description: Bookmark this to keep an eye on my project updates!
  
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: abhishesh
    github: abhishesh
    instagram: attaboyabhi
    linkedin: abhishesh
    keybase: abhishesh

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
