title: Abhishesh's Homepage

theme: minima

minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: abhishesh
    github: abhishesh
    linkedin: abhishesh
    keybase: abhishesh

plugins:
 - jekyll-feed
 - jekyll-seo-tag

google_analytics: G-K7SCW79J2L
